config/routes.rb
Rails.application.routes.draw do
  resources :circuit_simulations


  get 'general_summaries', to:"general_summaries#index", as:'general_summaries'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :questions
  get 'student_activities/:id/students/:student_id/questions/:question_id', to:'student_activities#question_evaluation', as:'student_question_evaluation'
  get 'student_activities/:id/students/:student_id', to:'student_activities#evaluation', as:'student_evaluation'
  resources :user_labs
  resources :student_summaries, only: [:show,:index]
  get 'student_activities/:id/groups', to: 'student_activities#groups', as:'activity_evaluation'
  resources :student_activities, only: [:show,:index]
  resources :activities

  get '/answer/:question_id/bad_selection', to: 'answers#bad_selection', as:'bad_selection'
  get '/answer/:question_id', to: 'answers#new', as:'answer_question'

  get '/', to:'activities#index'
end

app/models/activity.rb
class Activity < ApplicationRecord
  has_one :lab
  has_one :prelab
  belongs_to :course
  def self.chapters_by_number
    {1=>"capitulo 1 ",

                             2=>"capitulo 2",
                            3=>"capitulo 3",
                            4=>"capitulo 4"}
  end

end

app/models/bad_selection.rb
class BadSelection < ApplicationRecord
  belongs_to :question_option_selection
end

app/models/circuit.rb
class Circuit < ApplicationRecord
  belongs_to :prelab
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :user_courses
  has_many :users, through:  :user_courses
  has_many :groups

end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :course
  has_many :user_groups
  has_many :users, through: :user_groups
end

app/models/lab.rb
class Lab < ApplicationRecord
  has_one_attached :assignment
  has_many :user_labs
end

app/models/prelab.rb
class Prelab < ApplicationRecord
  belongs_to :activity
  has_many :circuits
  has_many :util_links
  has_many :prelab_questions
  has_many :questions, through: :prelab_questions
  accepts_nested_attributes_for :questions
  accepts_nested_attributes_for :circuits
  accepts_nested_attributes_for :util_links
  has_many_attached :datasheets

  def get_text_questions
    return self.questions.where(question_type:2)
  end

  def was_performed_by_user(user_id)
    user_prelab = UserPrelab.find_by(user_id:user_id,prelab_id:self.id)
    if user_prelab.nil?
      return false
    else
      return true
    end
  end

end

app/models/prelab_question.rb
class PrelabQuestion < ApplicationRecord
  belongs_to :prelab
  belongs_to :question
end

app/models/question.rb
class Question < ApplicationRecord
  @@MULTIPLE_SELECTION_TYPE=1
  @@TEXT_ANSWER_TYPE=2

  def is_multiple_selection
    if self.question_type==@@MULTIPLE_SELECTION_TYPE
      return true
    end
    return false
  end


  has_one_attached :question_image
  has_many :question_options
  accepts_nested_attributes_for :question_options

end

app/models/question_option.rb
class QuestionOption < ApplicationRecord
  belongs_to :question

  def get_option_name
    all_options=self.question.question_options
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_and_belongs_to_many :groups
end

app/models/user_course.rb
class UserCourse < ApplicationRecord
  belongs_to :course
  belongs_to :user
end

app/models/user_group.rb
class UserGroup < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/user_lab.rb
class UserLab < ApplicationRecord
  belongs_to :user
  belongs_to :lab
  has_one_attached :report

  def get_state
    if !self.report.attached?
      return false
    else
      return true
    end
  end
end

app/models/user_prelab.rb
class UserPrelab < ApplicationRecord
  belongs_to :user
  belongs_to :prelab
  has_many :question_option_selections
  has_many :question_text_answers

  def self.get_grade(user,prelab)
    user_prelab = UserPrelab.find_by(user:user,prelab:prelab)
    if user_prelab.nil?
      return 1
    else
      return 7
    end

  end

  def get_state
    questions= self.prelab.questions
    completed = true
    question_option_selections = self.question_option_selections
    questions.each do |question|

      if question.is_multiple_selection
        questions_options = QuestionOption.where(question:questions)
        if question_option_selections.where(question_option:questions_options).empty?
          completed=false
        end
      else
        question_text_answer = QuestionTextAnswer.find_by(user_prelab:self,question:question)
        if question_text_answer.nil?
          completed = false
        end
      end
    end

    return completed
  end

  def get_questions_grade
    grades_sum=0
    self.prelab.questions.each do |question|
      grades_count=0
      if question.is_multiple_selection
        grade=7
        correct_options = question.question_options.where(correct:true)

        question_option_selections = self.question_option_selections.where(question_option:question.question_options.collect{|r| r.id})
        if question_option_selections.empty? || question_option_selections.where(question_option:correct_options).empty?

          grades_sum+=1
          next
        else

          question_option_selections.each do |question_option_selection|
            if !question_option_selection.question_option.correct?
              grade-=1
            end
          end
          grades_sum+=grade
        end

      else

        question_answer = self.question_text_answers.find_by(question:question)
        grade = question_answer.grade
        if grade.nil?
          grades_sum+=1
        else
          grades_sum+=grade
        end
      end

    end

    questions_grade = grades_sum/self.prelab.questions.count

    return questions_grade
  end
end

app/models/util_link.rb
class UtilLink < ApplicationRecord
  belongs_to :prelab
end

app/controllers/student_activities_controller.rb
class StudentActivitiesController < ApplicationController
  before_action :set_activity, only:[:show,:groups,:evaluation,:update_question_evaluation,:question_evaluation]
  before_action :set_question, only:[:question_evaluation,:update_question_evaluation]
  before_action :set_student, only: [:evaluation,:question_evaluation,:update_question_evaluation]
  def show

  end

  def index

  end
  def update_question_evaluation
    user_prelab=UserPrelab.where(user_id:@student.id,prelab_id:@activity.prelab.id)
    QuestionTextAnswer.where(user_prelab_id:user_prelab.id,question:question)

  end

  def question_evaluation


  end
  def evaluation
    @user_lab = UserLab.find_by(lab_id: @lab.id,user_id:@student.id)
  end

  def groups


  end

  private
  def set_question
    @question=Question.find(params[:question_id])
  end
  private
  def set_activity

    @activity=Activity.find(params[:id])
    @lab=@activity.lab
  end

  private
  def set_student
    @student=User.find(params[:student_id])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/prelabs_helper.rb
module PrelabsHelper
end

app/helpers/student_activities_helper.rb
module StudentActivitiesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/student_activities/evaluation.html.erb
<br>

<h1  style="text-align: center">Evaluacion <%=@student.email%> </h1>

<br>
<h1 >Pre Laboratorio</h1>

<div class="prelab_eval">

  <label><b>Preguntas desarrollo:</b> </label>

  <ol>

  <%@activity.prelab.get_text_questions.each do |text_question|%>

    <li>
      <p>Question
      <%=link_to "Revisar",student_question_evaluation_path(id:@activity.id,student_id:@student.id,question_id:text_question.id) %>
      </p>
    </li>

  <%end%>

    <%=link_to "Ver resumen preguntas",student_summary_path(@student.id,:activity=>1)%>

  </ol>
    <label><b>Simulaciones:</b> </label>
<ol>
    <%@activity.prelab.circuits.each do |circuit|%>
    <%@user_prelab = UserPrelab.find_by(user:@student,prelab:@activity.prelab)%>
    <%cir_sim = CircuitSimulation.find_by(circuit:circuit,user_prelab_id: @user_prelab.id)%>
      <li>
        <p><%=circuit.name%>
          <%=link_to "Revisar", edit_circuit_simulation_path(cir_sim)%>
        </p>
      </li>

    <%end%>
</ol>

</div>

<br>
<h1>Laboratorio</h1>

<div class="lab_eval">
  <label for="nota_informe">Nota Informe: <%=@user_lab.report_grade%></label>
  <br>
  <label>Nota Participacion: <%=@user_lab.class_grade%> </label>
  <br>
  <label>Informe adjunto: <%= link_to 'Descargar', rails_blob_path(@user_lab.report, disposition: "attachment") || @user_lab.report%> </label>
  <br>
  <label>Nota Final Lab: <%=(@user_lab.report_grade+@user_lab.class_grade)/2%> </label>

  <br>
<%=link_to "Editar Notas",edit_user_lab_path(@user_lab)%>
</div>



<style>
  .prelab_eval, .lab_eval{

    border-style: groove;
    border-width: 1px;
    min-height: 35%;
    padding: 2% 2% 2% 2%;

  }


</style>

app/views/student_activities/groups.html.erb
<h1 class="module_title">Alumnos</h1>
<br>
<hr>
<br>
<%@activity.course.groups.each do |group|%>
  <h2> Grupo <%=group.number%></h2>
  <ul>
    <%group.users.each do |user|%>
      <li><%=link_to user.email,student_evaluation_path(id:@activity.id,student_id:user.id)%></li>
    <%end%>
  </ul>
<%end%>

app/views/student_activities/index.html.erb
<h1>StudentActivities#index</h1>


<p>Find me in app/views/student_activities/index.html.erb</p>

app/views/student_activities/question_evaluation.erb
<h1 class="module_title">Evaluacion Pregunta Desarrollo</h1>
<%@user_prelab=UserPrelab.find_by(user_id:@student.id,prelab_id:@activity.prelab.id)
@question_text_answer=QuestionTextAnswer.find_or_create_by(user_prelab_id:@user_prelab.id,question_id:@question.id)
%>

<div class="question_display">
  <h1>Pregunta #1</h1>

  <br>
  <div class=question_info>


    <p><%=@question.question_text%></p>

    <%if @question.question_image.attached?%>
      <%=image_tag @question.question_image, class:"question_image"%>
    <%end%>

    </br>
  </div>
  </br>

    <%=form_for @question_text_answer, :url=>"" do |f|%>

    <%=f.label :text_response, "Respuesta alumno: "%>
      <%=f.text_field :answer_text, class: 'text_area',:size => 150,:rows=>10, :readonly=>true%>

    <br>
    <%=f.label :grade, "Nota: "%>
    <%=f.text_field :grade %>

      </br>

      </br>
      <%=submit_tag "Actualizar nota", class:"submit"%>


    <%end%>

</div>

<style>
  .question_image{
    max-height: 40%;
    max-width: 40%;

  }

  .question_display{
    margin: 5% 15% 5% 15%;
    padding: 2%;
    border-style: groove  ;
    border-radius: 3px;
    border-color: rgba(63, 63, 63, 0.78);
    border-width: 1px;
    background-color: rgba(168, 167, 163, 0.19);

    padding: 2% 4% 2% 4%;

  }


  .question_display h1,p{

    text-align: center;
    margin-left: 5%;
    margin-right:  5%;

  }

  .question_info{
    border-style: groove  ;
    border-width: 1px;
    padding-top: 2%;
    background-color: rgba(0, 3, 115, 0.12);

  }
  .question_display img{

    margin-left: auto;
    margin-right: auto;
    display: block;
    border-radius: 10px;

  }
  .question_display .text_area{

    width: 95%;

    min-height:15ch;
  }

  .submit{

    margin-right: 0%;
    display: block;
    margin-left: auto;

  }
</style>

app/views/student_activities/show.html.erb
<h1>Actividad: <%=Activity.chapters_by_number[@activity.chapter]%></h1>
<hr>
<br>


<div class="util_links_div">
  <h5><u>Bibliografía</u></h5>

  <ul>
    <%@activity.prelab.util_links.each do |util_link|%>
      <li><%=link_to util_link.link,util_link.link%></li>

    <%end%>
  </ul>

<hr>


  <h5><u>Circuitos</u></h5>
  <ul>

  <%@activity.prelab.circuits.each do |circuit|%>

      <li> <%=circuit.name%> <%=link_to "Revisar adjunto",edit_circuit_simulation_path(1)%></li>

  <%end%>
  </ul>

  <!--<%=button_to "Editar Adjuntos",edit_circuit_simulation_path(1), style:"margin-bottom:0%"%>-->

  <%=button_to "Ir al Quizz",answer_question_path(1), :style=>"margin-right: 0%;display: block;margin-left: auto;",method: :get%>

</div>

<br>
<div class =util_links_div>
  <h5>Laboratorio</h5>

  <%=label_tag :assignment do%>
  <p>Enunciado: <%= link_to 'Descargar', rails_blob_path(@lab.assignment, disposition: "attachment") %>
  </p>
<%end%>
  <p>Informe:  <%=link_to 'Descargar',rails_blob_path(@lab.assignment,disposition:"attachment")%></p>

  <%=button_to 'Editar', edit_user_lab_path(@lab.user_labs.first), :method=>:get%>
 </div>
<style>
  .util_links_div, .circuits_div{

    border-style: groove;
    border-width: 1px;
    min-height: 35%;
    padding: 2% 2% 2% 2%;

  }

    .util_links_div{

    }

    .circuits_div{

    }

</style>