config/routes.rb
Rails.application.routes.draw do
  resources :circuit_simulations


  get 'general_summaries', to:"general_summaries#index", as:'general_summaries'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :questions
  get 'student_activities/:id/students/:student_id/questions/:question_id', to:'student_activities#question_evaluation', as:'student_question_evaluation'
  get 'student_activities/:id/students/:student_id', to:'student_activities#evaluation', as:'student_evaluation'
  resources :user_labs
  resources :student_summaries, only: [:show,:index]
  get 'student_activities/:id/groups', to: 'student_activities#groups', as:'activity_evaluation'
  resources :student_activities, only: [:show,:index]
  resources :activities

  get '/answer/:question_id/bad_selection', to: 'answers#bad_selection', as:'bad_selection'
  get '/answer/:question_id', to: 'answers#new', as:'answer_question'

  get '/', to:'activities#index'
end

app/models/activity.rb
class Activity < ApplicationRecord
  has_one :lab
  has_one :prelab
  belongs_to :course
  def self.chapters_by_number
    {1=>"capitulo 1 ",

                             2=>"capitulo 2",
                            3=>"capitulo 3",
                            4=>"capitulo 4"}
  end

end

app/models/bad_selection.rb
class BadSelection < ApplicationRecord
  belongs_to :question_option_selection
end

app/models/circuit.rb
class Circuit < ApplicationRecord
  belongs_to :prelab
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :user_courses
  has_many :users, through:  :user_courses
  has_many :groups

end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :course
  has_many :user_groups
  has_many :users, through: :user_groups
end

app/models/lab.rb
class Lab < ApplicationRecord
  has_one_attached :assignment
  has_many :user_labs
end

app/models/prelab.rb
class Prelab < ApplicationRecord
  belongs_to :activity
  has_many :circuits
  has_many :util_links
  has_many :prelab_questions
  has_many :questions, through: :prelab_questions
  accepts_nested_attributes_for :questions
  accepts_nested_attributes_for :circuits
  accepts_nested_attributes_for :util_links
  has_many_attached :datasheets

  def get_text_questions
    return self.questions.where(question_type:2)
  end

  def was_performed_by_user(user_id)
    user_prelab = UserPrelab.find_by(user_id:user_id,prelab_id:self.id)
    if user_prelab.nil?
      return false
    else
      return true
    end
  end

end

app/models/prelab_question.rb
class PrelabQuestion < ApplicationRecord
  belongs_to :prelab
  belongs_to :question
end

app/models/question.rb
class Question < ApplicationRecord
  @@MULTIPLE_SELECTION_TYPE=1
  @@TEXT_ANSWER_TYPE=2

  def is_multiple_selection
    if self.question_type==@@MULTIPLE_SELECTION_TYPE
      return true
    end
    return false
  end


  has_one_attached :question_image
  has_many :question_options
  accepts_nested_attributes_for :question_options

end

app/models/question_option.rb
class QuestionOption < ApplicationRecord
  belongs_to :question

  def get_option_name
    all_options=self.question.question_options
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_and_belongs_to_many :groups
end

app/models/user_course.rb
class UserCourse < ApplicationRecord
  belongs_to :course
  belongs_to :user
end

app/models/user_group.rb
class UserGroup < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/user_lab.rb
class UserLab < ApplicationRecord
  belongs_to :user
  belongs_to :lab
  has_one_attached :report

  def get_state
    if !self.report.attached?
      return false
    else
      return true
    end
  end
end

app/models/user_prelab.rb
class UserPrelab < ApplicationRecord
  belongs_to :user
  belongs_to :prelab
  has_many :question_option_selections
  has_many :question_text_answers

  def self.get_grade(user,prelab)
    user_prelab = UserPrelab.find_by(user:user,prelab:prelab)
    if user_prelab.nil?
      return 1
    else
      return 7
    end

  end

  def get_state
    questions= self.prelab.questions
    completed = true
    question_option_selections = self.question_option_selections
    questions.each do |question|

      if question.is_multiple_selection
        questions_options = QuestionOption.where(question:questions)
        if question_option_selections.where(question_option:questions_options).empty?
          completed=false
        end
      else
        question_text_answer = QuestionTextAnswer.find_by(user_prelab:self,question:question)
        if question_text_answer.nil?
          completed = false
        end
      end
    end

    return completed
  end

  def get_questions_grade
    grades_sum=0
    self.prelab.questions.each do |question|
      grades_count=0
      if question.is_multiple_selection
        grade=7
        correct_options = question.question_options.where(correct:true)

        question_option_selections = self.question_option_selections.where(question_option:question.question_options.collect{|r| r.id})
        if question_option_selections.empty? || question_option_selections.where(question_option:correct_options).empty?

          grades_sum+=1
          next
        else

          question_option_selections.each do |question_option_selection|
            if !question_option_selection.question_option.correct?
              grade-=1
            end
          end
          grades_sum+=grade
        end

      else

        question_answer = self.question_text_answers.find_by(question:question)
        grade = question_answer.grade
        if grade.nil?
          grades_sum+=1
        else
          grades_sum+=grade
        end
      end

    end

    questions_grade = grades_sum/self.prelab.questions.count

    return questions_grade
  end
end

app/models/util_link.rb
class UtilLink < ApplicationRecord
  belongs_to :prelab
end

app/controllers/user_labs_controller.rb
class UserLabsController < ApplicationController
  before_action :set_user_lab, only: [:show, :edit, :update, :destroy]

  # GET /user_labs
  # GET /user_labs.json
  def index
    @user_labs = UserLab.all
  end

  # GET /user_labs/1
  # GET /user_labs/1.json
  def show
  end

  # GET /user_labs/new
  def new
    @user_lab = UserLab.new
  end

  # GET /user_labs/1/edit
  def edit
  end

  # POST /user_labs
  # POST /user_labs.json
  def create
    @user_lab = UserLab.new(user_lab_params)

    respond_to do |format|
      if @user_lab.save
        format.html { redirect_to @user_lab, notice: 'User lab was successfully created.' }
        format.json { render :show, status: :created, location: @user_lab }
      else
        format.html { render :new }
        format.json { render json: @user_lab.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_labs/1
  # PATCH/PUT /user_labs/1.json
  def update
    respond_to do |format|
      if @user_lab.update(user_lab_params)
        format.html { redirect_to @user_lab, notice: 'User lab was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_lab }
      else
        format.html { render :edit }
        format.json { render json: @user_lab.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_labs/1
  # DELETE /user_labs/1.json
  def destroy
    @user_lab.destroy
    respond_to do |format|
      format.html { redirect_to user_labs_url, notice: 'User lab was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_lab
      @user_lab = UserLab.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_lab_params
      params.require(:user_lab).permit(:user_id, :lab_id, :class_grade, :report_grade)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/prelabs_helper.rb
module PrelabsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/user_labs_helper.rb
module UserLabsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/user_labs/_form.html.erb
<%= form_with(model: user_lab, local: true) do |form| %>
  <% if user_lab.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_lab.errors.count, "error") %> prohibited this user_lab from being saved:</h2>

      <ul>
      <% user_lab.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!--<div class="field">-->
    <!--<%= form.label :user_id %>-->
    <!--<%= form.text_field :user_id %>-->
  <!--</div>-->

  <!--<div class="field">-->
    <!--<%= form.label :lab_id %>-->
    <!--<%= form.text_field :lab_id %>-->
  <!--</div>-->

  <div class="field">
    <%= label_tag :report_link,"(AE) Informe actual : "%>
    <%= link_to "Descargar", rails_blob_path(@user_lab.report,disposition:"attachment")%>

  </div>


  <div class="field">
    <%= label_tag :report,"(A) Subir informe: "%>
    <%= form.file_field :report %>

  </div>

  <div class="field">
    <%= form.label :report_grade, "(E)Nota Informe" %>
    <%= form.number_field :report_grade %>
  </div>

  <div class="field">
    <%= form.label :class_grade,"(E)Nota clase" %>
    <%= form.number_field :class_grade %>
  </div>

  <div class="actions">
    <%= form.submit "Aceptar" %>
  </div>
<% end %>

app/views/user_labs/_student_form.html.erb
<%= form_with(model: user_lab, local: true) do |form| %>
  <% if user_lab.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_lab.errors.count, "error") %> prohibited this user_lab from being saved:</h2>

      <ul>
        <% user_lab.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <!--<div class="field">-->
  <!--<%= form.label :user_id %>-->
  <!--<%= form.text_field :user_id %>-->
  <!--</div>-->

  <!--<div class="field">-->
  <!--<%= form.label :lab_id %>-->
  <!--<%= form.text_field :lab_id %>-->
  <!--</div>-->

  <div class="field">
    <%= label_tag :report_link,"Informe actual: "%>
    <%= link_to "Descargar", rails_blob_path(@user_lab.report,disposition:"attachment")%>

  </div>


  <div class="field">
    <%= label_tag :report,"Subir informe: "%>
    <%= form.file_field :report %>

  </div>

  <div class="actions">
    <%= form.submit "Aceptar" %>
  </div>
<% end %>

app/views/user_labs/edit.html.erb
<h1>Editar Laboratorio <%=@user_lab.user.email%></h1>
<hr>
<br>
<%= render 'form', user_lab: @user_lab %>

<%#= link_to 'Show', @user_lab %>
<%#= link_to 'Back', user_labs_path %>

app/views/user_labs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Labs</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Lab</th>
      <th>Class grade</th>
      <th>Report grade</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_labs.each do |user_lab| %>
      <tr>
        <td><%= user_lab.user %></td>
        <td><%= user_lab.lab %></td>
        <td><%= user_lab.class_grade %></td>
        <td><%= user_lab.report_grade %></td>
        <td><%= link_to 'Show', user_lab %></td>
        <td><%= link_to 'Edit', edit_user_lab_path(user_lab) %></td>
        <td><%= link_to 'Destroy', user_lab, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User Lab', new_user_lab_path %>

app/views/user_labs/new.html.erb
<h1>New User Lab</h1>

<%= render 'form', user_lab: @user_lab %>

<%= link_to 'Back', user_labs_path %>

app/views/user_labs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user_lab.user %>
</p>

<p>
  <strong>Lab:</strong>
  <%= @user_lab.lab %>
</p>

<p>
  <strong>Class grade:</strong>
  <%= @user_lab.class_grade %>
</p>

<p>
  <strong>Report grade:</strong>
  <%= @user_lab.report_grade %>
</p>

<%= link_to 'Edit', edit_user_lab_path(@user_lab) %> |
<%= link_to 'Back', user_labs_path %>