config/routes.rb
Rails.application.routes.draw do
  resources :circuit_simulations


  get 'general_summaries', to:"general_summaries#index", as:'general_summaries'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :questions
  get 'student_activities/:id/students/:student_id/questions/:question_id', to:'student_activities#question_evaluation', as:'student_question_evaluation'
  get 'student_activities/:id/students/:student_id', to:'student_activities#evaluation', as:'student_evaluation'
  resources :user_labs
  resources :student_summaries, only: [:show,:index]
  get 'student_activities/:id/groups', to: 'student_activities#groups', as:'activity_evaluation'
  resources :student_activities, only: [:show,:index]
  resources :activities

  get '/answer/:question_id/bad_selection', to: 'answers#bad_selection', as:'bad_selection'
  get '/answer/:question_id', to: 'answers#new', as:'answer_question'

  get '/', to:'activities#index'
end

app/models/activity.rb
class Activity < ApplicationRecord
  has_one :lab
  has_one :prelab
  belongs_to :course
  def self.chapters_by_number
    {1=>"capitulo 1 ",

                             2=>"capitulo 2",
                            3=>"capitulo 3",
                            4=>"capitulo 4"}
  end

end

app/models/bad_selection.rb
class BadSelection < ApplicationRecord
  belongs_to :question_option_selection
end

app/models/circuit.rb
class Circuit < ApplicationRecord
  belongs_to :prelab
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :user_courses
  has_many :users, through:  :user_courses
  has_many :groups

end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :course
  has_many :user_groups
  has_many :users, through: :user_groups
end

app/models/lab.rb
class Lab < ApplicationRecord
  has_one_attached :assignment
  has_many :user_labs
end

app/models/prelab.rb
class Prelab < ApplicationRecord
  belongs_to :activity
  has_many :circuits
  has_many :util_links
  has_many :prelab_questions
  has_many :questions, through: :prelab_questions
  accepts_nested_attributes_for :questions
  accepts_nested_attributes_for :circuits
  accepts_nested_attributes_for :util_links
  has_many_attached :datasheets

  def get_text_questions
    return self.questions.where(question_type:2)
  end

  def was_performed_by_user(user_id)
    user_prelab = UserPrelab.find_by(user_id:user_id,prelab_id:self.id)
    if user_prelab.nil?
      return false
    else
      return true
    end
  end

end

app/models/prelab_question.rb
class PrelabQuestion < ApplicationRecord
  belongs_to :prelab
  belongs_to :question
end

app/models/question.rb
class Question < ApplicationRecord
  @@MULTIPLE_SELECTION_TYPE=1
  @@TEXT_ANSWER_TYPE=2

  def is_multiple_selection
    if self.question_type==@@MULTIPLE_SELECTION_TYPE
      return true
    end
    return false
  end


  has_one_attached :question_image
  has_many :question_options
  accepts_nested_attributes_for :question_options

end

app/models/question_option.rb
class QuestionOption < ApplicationRecord
  belongs_to :question

  def get_option_name
    all_options=self.question.question_options
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_and_belongs_to_many :groups
end

app/models/user_course.rb
class UserCourse < ApplicationRecord
  belongs_to :course
  belongs_to :user
end

app/models/user_group.rb
class UserGroup < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/user_lab.rb
class UserLab < ApplicationRecord
  belongs_to :user
  belongs_to :lab
  has_one_attached :report

  def get_state
    if !self.report.attached?
      return false
    else
      return true
    end
  end
end

app/models/user_prelab.rb
class UserPrelab < ApplicationRecord
  belongs_to :user
  belongs_to :prelab
  has_many :question_option_selections
  has_many :question_text_answers

  def self.get_grade(user,prelab)
    user_prelab = UserPrelab.find_by(user:user,prelab:prelab)
    if user_prelab.nil?
      return 1
    else
      return 7
    end

  end

  def get_state
    questions= self.prelab.questions
    completed = true
    question_option_selections = self.question_option_selections
    questions.each do |question|

      if question.is_multiple_selection
        questions_options = QuestionOption.where(question:questions)
        if question_option_selections.where(question_option:questions_options).empty?
          completed=false
        end
      else
        question_text_answer = QuestionTextAnswer.find_by(user_prelab:self,question:question)
        if question_text_answer.nil?
          completed = false
        end
      end
    end

    return completed
  end

  def get_questions_grade
    grades_sum=0
    self.prelab.questions.each do |question|
      grades_count=0
      if question.is_multiple_selection
        grade=7
        correct_options = question.question_options.where(correct:true)

        question_option_selections = self.question_option_selections.where(question_option:question.question_options.collect{|r| r.id})
        if question_option_selections.empty? || question_option_selections.where(question_option:correct_options).empty?

          grades_sum+=1
          next
        else

          question_option_selections.each do |question_option_selection|
            if !question_option_selection.question_option.correct?
              grade-=1
            end
          end
          grades_sum+=grade
        end

      else

        question_answer = self.question_text_answers.find_by(question:question)
        grade = question_answer.grade
        if grade.nil?
          grades_sum+=1
        else
          grades_sum+=grade
        end
      end

    end

    questions_grade = grades_sum/self.prelab.questions.count

    return questions_grade
  end
end

app/models/util_link.rb
class UtilLink < ApplicationRecord
  belongs_to :prelab
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]

  # GET /activities
  # GET /activities.json
  def index
    @activities = Activity.all
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(activity_params)

    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, notice: 'Activity was successfully created.' }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url, notice: 'Activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.require(:activity).permit(:chapter)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/prelabs_helper.rb
module PrelabsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/activities/_form.html.erb
<%= form_with(model: activity, local: true) do |form| %>
  <% if activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
      <% activity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :chapter %>
    <%= form.number_field :chapter, id: :activity_chapter %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/activities/edit.html.erb
<h1>Editing Activity</h1>

<%= render 'form', activity: @activity %>

<%= link_to 'Show', @activity %> |
<%= link_to 'Back', activities_path %>

app/views/activities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Activities</h1>

<table class ="table">
  <thead>
    <tr>
      <th>Chapter</th>
      <th>Inicio</th>
      <th>Fin</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @activities.each do |activity| %>
      <tr>
        <td><%= activity.chapter %></td>
        <td><%= if !activity.prelab.nil? then activity.prelab.begin.to_date end%></td>

        <td><%= if !activity.lab.nil? and !activity.lab.begin.nil? then activity.lab.begin.to_date else 'Sin Info' end%></td>


        <td><%= link_to 'Entrar (alumno)', student_activity_path(id:activity.id,student_id:1) %> </td>
        <td><%= link_to 'Entrar (evaluador)', activity_evaluation_path(activity) %> </td>
        <!--<td><%= link_to 'Edit', edit_activity_path(activity) %> |</td>-->
        <!--<td><%= link_to 'Destroy', activity, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/activities/new.html.erb
<h1>New Activity</h1>

<%= render 'form', activity: @activity %>

<%= link_to 'Back', activities_path %>

app/views/activities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Chapter:</strong>
  <%= @activity.chapter %>
</p>

<%= link_to 'Edit', edit_activity_path(@activity) %> |
<%= link_to 'Back', activities_path %>